In [88]:
import numpy as np

import scipy.linalg as la
import scipy.sparse.linalg as sparse

# Problem 8
$$ - \left( \frac{\partial^2 u}{\partial x^2} + \frac{\partial^2 u}{\partial y^2} \right) - e^u = 0$$
Leads to the FD equation
$$4u_{i,j} - u_{i-1,j} - u_{i+1,j} - u_{i,j-1} - u_{i,j+1} - h^2e^{u_{i,j}} = 0$$
for $ 0< i,j < n$
$$f(\vec{u}) = A\vec{u} - e^\vec{u} = 0$$
So the Jacobian is given by the following formulae
$$
\frac{\partial f}{\partial u_{i,j}} = 4 - h^2e^{u_{i,j}}
$$

In [100]:
N = 3
n = N**2
h = 1/(N+1)

a = .1
iter_max = 10**5
tol = 10**-6


J = np.diag([4]*N) + np.diag([-1]*(N-1),k=-1) + np.diag([-1]*(N-1),k=1)
K = np.diag([-1]*N)
shape_matrix = np.diag([1]*(N-1),k=-1) + np.diag([1]*(N-1),k=1)
A = np.kron(shape_matrix,K) + np.kron(np.eye(N),J)

# generate initial u
X = np.linspace(h,1-h,N)
u = np.array([ a*x*(1-x)*(1-y) for x in X for y in X]).reshape((n,1))

#u = np.ones((n,1))
Jac = A - np.diag(h**2*np.exp(u).ravel())
u_new = la.solve(Jac, h**2*np.exp(u) - np.dot(A,u))
for iteration in range(1,iter_max+1):
    if la.norm(u_new-u) < tol*n:
        break
    u = u_new
    Jac = A - np.diag(h**2*np.exp(u).ravel())
    u_new = la.solve(Jac, h**2*np.exp(u) - np.dot(A,u))
    
print(iteration)
    

21712


In [90]:
u_new

array([ 0.02263589,  0.02893338,  0.02260557,  0.02892781,  0.03733704,
        0.02895132,  0.02263589,  0.02893338,  0.02260557])

In [81]:
for i in range(10**4):
    u = u_new
    Jac = A - np.diag(h**2*np.exp(u).ravel())
    u_new = la.solve(Jac, h**2*np.exp(u) - np.dot(A,u))

In [82]:
u_new

array([[ 0.02263471],
       [ 0.02892799],
       [ 0.02263564],
       [ 0.02892839],
       [ 0.03733947],
       [ 0.02892757],
       [ 0.02263471],
       [ 0.02892799],
       [ 0.02263564]])

In [37]:
Jac

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [27]:
u

array([ 1.,  1.,  1.,  1.])

In [65]:
x = np.linspace(h, 1-h, N)

In [66]:
x

array([ 0.25,  0.5 ,  0.75])

In [68]:
u = [ a*x*(1-x)*(1-y) for x in X for y in X]

In [69]:
u

[0.0703125,
 0.046875,
 0.0234375,
 0.09375,
 0.0625,
 0.03125,
 0.0703125,
 0.046875,
 0.0234375]

In [95]:
u = np.array([ a*x*(1-x)*(1-y) for x in X for y in X]).reshape((n,1))
print(u)

[[ 0.0140625]
 [ 0.009375 ]
 [ 0.0046875]
 [ 0.01875  ]
 [ 0.0125   ]
 [ 0.00625  ]
 [ 0.0140625]
 [ 0.009375 ]
 [ 0.0046875]]


In [96]:
Jac = A - np.diag(h**2*np.exp(u).ravel())
print(Jac)

[[ 3.93661488 -1.          0.         -1.          0.          0.          0.
   0.          0.        ]
 [-1.          3.93691131 -1.          0.         -1.          0.          0.
   0.          0.        ]
 [ 0.         -1.          3.93720634  0.          0.         -1.          0.
   0.          0.        ]
 [-1.          0.          0.          3.93631707 -1.          0.         -1.
   0.          0.        ]
 [ 0.         -1.          0.         -1.          3.93671385 -1.          0.
  -1.          0.        ]
 [ 0.          0.         -1.          0.         -1.          3.93710815
   0.          0.         -1.        ]
 [ 0.          0.          0.         -1.          0.          0.
   3.93661488 -1.          0.        ]
 [ 0.          0.          0.          0.         -1.          0.         -1.
   3.93691131 -1.        ]
 [ 0.          0.          0.          0.          0.         -1.          0.
  -1.          3.93720634]]
