In [1]:
import numpy as np

In [8]:
A = np.ones( (5,3) )
Q,R = np.linalg.qr(A)
print(Q)
print(R)
print(np.allclose(A, Q.dot(R)))

[[-4.47213595e-01  8.94427191e-01 -4.01682464e-17]
 [-4.47213595e-01 -2.23606798e-01 -5.00000000e-01]
 [-4.47213595e-01 -2.23606798e-01  8.33333333e-01]
 [-4.47213595e-01 -2.23606798e-01 -1.66666667e-01]
 [-4.47213595e-01 -2.23606798e-01 -1.66666667e-01]]
[[-2.23606798e+00 -2.23606798e+00 -2.23606798e+00]
 [ 0.00000000e+00 -2.22044605e-16 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
True


In [10]:
Q.dot(R)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])